# Generated by Django 4.1.5 on 2023-03-10 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_amenities_alter_room_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='kind',
            field=models.CharField(choices=[('entire_place', 'Entire_place'), ('private_place', 'Private_place'), ('shared_room', 'Shared_room')], max_length=20),
        ),
    ]
